### ISSUE TITLE
Empty password should be VERY_WEAK

### ISSUE THREAD

**Issue by cyberwombat** [tests-always-included/password-strength#18]
Right now an empty password doesn't return a strength code which seems weird. I would expect an empty password to be VERY_WEAK instead of me having to first check that the strengthCode !== null.

What are your thoughts?

**Comment by fidian** [comment]
I can understand your viewpoint.

From a mathematical perspective, I feel that a zero score is better than any number, and `null` is as close as I can get to zero. From a programmer's perspective, I find it hard to justify that an empty password has any strength at all. Even default passwords or single character passwords are stronger. Also from a programmer's perspective, I could argue that an empty string contains no password, and thus can't be measured.

I'm envisioning this tool used on those password change screens. Two input boxes above each other. The top one is separated by a bit of a space or has some whitespace to the side. When the user types in a new password, icons and messages can show up. When there is no input, we want nothing displayed. In this scenario we also want to probably have a value that isn't `VERY_WEAK`, or else we'd have to say `if (password.length > 0)` or similar logic. You could also have logic to change the form to make it red when it says `VERY_WEAK` or `WEAK`. That way the form doesn't look like it's invalid when there's no password.

I won't be changing this any time soon. I did *seriously* think about it for a while before I came to that decision, then I thought about it all again today. Thank you for the feedback. If others have the same point of view and this is a recurring theme, I will revisit the decision yet again.

**Comment by cyberwombat** [comment]
I can see how that makes sense in the browser yes which is not where (yet) I was using it. It threw me for a loop in my tests when it broken on no pass. I''ll just do a check to ensure there is a `results.strengthCode` value.

Thanks.
