### ISSUE TITLE
Strength code doesn't make sense

### ISSUE THREAD

**Issue by maxsummers** [tests-always-included/password-strength#4]
Thanks for the module, it looks great.

But, after testing it, I can say, that strength code doesn't make sense to me at all.

`Abcdefghij => REASONABLE`
`1fk8x8Pydt => REASONABLE`

How alphabetical sequence of letters could be considered **reasonable** and be in the same category of strength with totally random sequence of letters and digits in various case?

**Comment by fidian** [comment]
Doesn't the documentation for this calculation help out?

https://github.com/tests-always-included/password-strength/blob/master/doc/entropy-seems-wrong.md

**Comment by fidian** [comment]
Closing because there was no response.
