### ISSUE TITLE
Browser example in README throws an error

### ISSUE THREAD

**Issue by scottwestover** [tests-always-included/password-strength#8]
In the README file, under the Browser example, it has the following code:

`$(function () {
    // Create the instance that can be used immediately for strength tests
    window.passwordStrength = new PasswordStrength();

    // Add additional files that improve the results
    $.getJSON("path/to/data/common-passwords.json", function (data) {
        window.passwordStrength.addCommonPasswords(data);
    });
    $.getJSON("path/to/data/trigraphs.json", function (data) {
        window.passwordStrength.addCommonPasswords(data);
    });
});`

However, after updating the paths to the json files, an error is thrown about the data being in the wrong format. 

I update the method for the trigraphs.json to be addTrigraphMap, and no errors are now being displayed. Here is the code that I am using: 

`$(function () {
    // Create the instance that can be used immediately for strength tests
    window.passwordStrength = new PasswordStrength();

    // Add additional files that improve the results
    $.getJSON("path/to/data/common-passwords.json", function (data) {
        window.passwordStrength.addCommonPasswords(data);
    });
    $.getJSON("path/to/data/trigraphs.json", function (data) {
        window.passwordStrength.addTrigraphMap(data);
    });
});`

**Comment by fidian** [comment]
Released the new version as 1.1.1. It also switches the linter and makes the tests pass.

I really appreciate the time you took to not only report the issue but to also submit a patch. Thank you!
